export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const UPDATE_CURRENT_PACKAGE = "UPDATE_CURRENT_PACKAGE";
export const UPDATE_ROUTE = "UPDATE_ROUTE";
export const UPDATE_PACKAGE_SELECTED = "UPDATE_PACKAGE_SELECTED";
export const UPDATE_CART_ITEM_CATEGORIES = "UPDATE_CART_ITEM_CATEGORIES";
export const UPDATE_TRACK_CHECKOUT = "UPDATE_TRACK_CHECKOUT";
export const UPDATE_DATE = "UPDATE_DATE";
export const UPDATE_CART_ITEM_BYID = "UPDATE_CART_ITEM_BYID";
export const UPDATE_COLOR = "UPDATE_COLOR"; 
export const UPDATE_BY_ID = "UPDATE_BY_ID";
export const UPDATE_CART_ITEM_BY_IDCACHE = "UPDATE_CART_ITEM_BY_IDCACHE";
export const UPDATE_COLORS = "UPDATE_COLORS";
export const UPDATE_CART_COLORS = "UPDATE_CART_COLORS"
export const UPDATE_PACKAGES = "UPDATE_PACKAGES"
export const UPDATE_VALIDATE_CART_HASH = "UPDATE_VALIDATE_CART_HASH"
export const SET_TRACK_CHECKOUT = "SET_TRACK_CHECKOUT"
